configuration.ini, db_blacklist.py, db_cpe_browser.py, db_dump.py, db_fulltext.py, db_mgmt.py, db_mgmt_cpe_dictionary.py, db_mgmt_cpe_other_dictionary.py, db_mgmt_create_index.py, db_mgmt_cwe.py, db_mgmt_d2sec.py, db_mgmt_vendorstatements.py, db_mgmt_vfeed.py, db_notification.py, db_ranking.py, db_updater.py, db_whitelist.py, dump_last.py, lib/cves.py, lib/list.py, search.py, search_cpe.py, search_fulltext.py, search_xmpp.py, web/index.py, web/templates/list.html
Updates:
- Updating CPE's in black/- and whitelist, instead of having to manually remove and re-add
- Put settings in a configuration file, instead of hardcoded
- Allow scripts to be called from any place on the system (by using os.path.dirname(sys.argv[0]))
=> Enhancements

configuration.ini, db_blacklist.py, db_cpe_browser.py, db_dump.py, db_fulltext.py, db_mgmt.py, db_mgmt_cpe_dictionary.py, db_mgmt_cpe_other_dictionary.py, db_mgmt_create_index.py, db_mgmt_cwe.py, db_mgmt_d2sec.py, db_mgmt_vendorstatements.py, db_mgmt_vfeed.py, db_notification.py, db_ranking.py, db_updater.py, db_whitelist.py, dump_last.py, lib/cves.py, lib/list.py, search.py, search_cpe.py, search_fulltext.py, search_xmpp.py, web/index.py
The configuration file should now be complete, and I also fixed a bug that would make you unable to run the index.py module from within web, only from any other place on the system.
=> Bugfixes + finalizing configuration file

web/index.py
Small but critical bug-fix for correct data
=> fix the query for the blacklist: solves issue #3

configuration.ini, db_mgmt.py, web/index.py, web/templates/browse.html, web/templates/index.html, web/templates/listmanagement.html
Bugfixing
--------
* Browse per vendor crash fixed
* Negative page numbers fixed
Optimization
---------
* Default cvss in config file
* Page length as an config
* Removing abundant function
* Fixing variable not read from config
=> Bugfixing and Optimization

Documentation/Webcomponent.html, Documentation/css/style.css, search_fulltext.py
HTML based documentation for CVE-Search (Web component)
=> Documentation

db_mgmt.py, lib/Config.py, search.py, search_cpe.py
Documentation
-----
* Documentation for the installation
* Documentation for setting up and using the webserver
Optimization
-----
* Usage of Config.py in cves.py
* Connection of cpeother to the rest of the project
* Relative path for the fulltext indexer in db_update.py
=> Documentation + Optimization

lib/list.py, web/index.py, web/static/js/custom/admin.js, web/templates/admin.html
File chooser for web interface allows for uploading from clients to server, instead of "on-server-access".
=> File chooser for web interface

configuration.ini, db_mgmt_capec.py, lib/Config.py
Addition of the CAPEC import script
Modification of the configuration files to add the CAPEC dictionary
=> New Feature : CAPEC import script

bin/db_mgmt.py, bin/db_mgmt_cpe_dictionary.py, lib/Toolkit.py, test/test.py, web/index.py, web/templates/admin.html
* Empty collection causes crash on admin page bugfix
* Update CPE format
Note: Do I leave the test script in there or not? The script helps to check if commits don't ruin working functions
=> Development + Bugfixes

bin/db_cpe_browser.py, web/index.py
* Error handling on Redis not running
* CVEs for CPE api request
=> Development + Error Handling

web/index.py, web/minimal-web.py
This allows other tools using the api (eg CVE-Scan) to work on a higher level
=> vFeed info in cvesfor

etc/configuration.ini.sample, lib/Config.py, requirements.txt, sbin/db_mgmt_ms.py, sbin/db_updater.py
Get ms-bulletin from Microsoft and add them in the collection 'ms'
New requirement xlrd to parse xls
=> Add MS-Bulletin

sbin/db_mgmt_ref.py
using the Configuration.getFile instead of urlopen for the proxy if needed"
=> fetch with std methods

etc/configuration.ini.sample, lib/Config.py, sbin/db_mgmt_cpe_other_dictionary.py, sbin/db_mgmt_ms.py, sbin/db_mgmt_ref.py, sbin/db_mgmt_vfeed.py
open question:
in sbin/db_mgmt_ms.py, the directory is removed at the end, which I found a bit not wanted. So I also comment it? Shouldn't this be a global parameter, also used by vfeed? What do you think?
=> move sme './tmp/' to config file.

sbin/db_mgmt_create_index.py, web/index.py, web/templates/table.html
Better overview failed indexes, remove debugging prints and display more of the summary
=> Little tweaks

lib/CVEs.py, lib/DatabaseLayer.py, lib/Query.py, sbin/db_cpe_browser.py, sbin/db_mgmt_cwe.py, sbin/db_mgmt_exploitdb.py, sbin/db_mgmt_vendorstatements.py, sbin/db_mgmt_vfeed.py, sbin/db_notification.py, sbin/db_ranking.py
With this, the database layer should be complete. Can you check, before pushing to the main repo?
=> finalizing the database layer

lib/DatabaseLayer.py, sbin/db_updater.py, web/index.py, web/static/css/style.css, web/static/js/custom/cve.js, web/static/js/custom/scripts.js, web/templates/capec.html, web/templates/cve.html, web/templates/cwe.html, web/templates/menu-minimal.html, web/templates/menu.html
Adding an initial CWE/CAPEC dictionary in the web interface
=> CWE & CAPEC Browser

etc/plugins.txt.sample, lib/DatabaseLayer.py, web/static/js/custom/admin.js, web/static/js/custom/statusses.js, web/templates/index.html
Flask-PyMongo 3.x vs 4.x changed [] to None when a find_one returns nothing.
=> Compatibiliy bugfix for Flask-PyMongo

lib/DatabaseLayer.py, lib/User.py, web/api.py, web/index.py, web/static/js/custom/admin.js, web/static/js/custom/statusses.js, web/templates/admin.html, web/templates/cve.html, web/templates/layouts/master-page
* Password change in Web interface
* Drop option for plug-in collections
* Remove plug-ins code from minimal web interface
=> Features and fixes

lib/Config.py, lib/DatabaseLayer.py
- Rework of getMongoConnection() function to correctly catch exceptions due to changes in PyMongo 2.9 and later
- getCVEStartYear() cleaned
- getMaxLogSize(): default values should be in MB, .lower() replaced by .upper() as b, kb can be confusing when referring to bytes
- getCVEStartYear, getMaxLogSize has been polished
=> Update of Config.py
